import os

PASSENGER_ID_COLUMN = "Passenger ID"
PASSENGER_FIRST_NAME_COLUMN = "Passenger First Name"
PASSENGER_LAST_NAME_COLUMN = "Passenger Last Name"
GENDER_COLUMN = "Gender"
AGE_COLUMN = "Age"
NATIONALITY_COLUMN = "Nationality"
DEPARTURE_AIRPORT_NAME_COLUMN = "Departure Airport Name"
DEPARTURE_AIRPORT_CODE_COLUMN = "Departure Airport Code"
DEPARTURE_COUNTRY_NAME_COLUMN = "Departure Country Name"
DEPARTURE_DATE_COLUMN = "Departure Date"
ARRIVAL_AIRPORT_NAME_COLUMN = "Arrival Airport Name"
ARRIVAL_AIRPORT_CODE_COLUMN = "Arrival Airport Code"
ARRIVAL_COUNTRY_NAME_COLUMN = "Arrival Country Name"
FLIGHT_STATUS_COLUMN = "Flight Status"
PILOT_FIRST_NAME_COLUMN = "Pilot First Name"
PILOT_LAST_NAME_COLUMN = "Pilot Last Name"

TEXT_COLUMNS = [
    PASSENGER_FIRST_NAME_COLUMN, PASSENGER_LAST_NAME_COLUMN, GENDER_COLUMN, NATIONALITY_COLUMN, DEPARTURE_AIRPORT_NAME_COLUMN, DEPARTURE_COUNTRY_NAME_COLUMN, ARRIVAL_AIRPORT_NAME_COLUMN, ARRIVAL_COUNTRY_NAME_COLUMN, PILOT_FIRST_NAME_COLUMN, PILOT_LAST_NAME_COLUMN, FLIGHT_STATUS_COLUMN
]

FLIGHTS_TABLE = "flights"
PASSENGERS_TABLE = "passengers"
AIRPORTS_TABLE = "airports"
COUNTRIES_TABLE = "countries"
PILOTS_TABLE = "pilots"
DATES_TABLE = "dates"
FLIGHT_STATUSES_TABLE = "flight_statuses"
DB_URL = "postgresql://postgres:postgres@localhost:5432/flights"
FLIGHTS_CSV_PATH = "data/dataset.csv"

DTYPE_DICT = {
    PASSENGER_ID_COLUMN: "object",
    PASSENGER_FIRST_NAME_COLUMN: "object",
    PASSENGER_LAST_NAME_COLUMN: "object",
    GENDER_COLUMN: "category",
    AGE_COLUMN: "Int64",
    NATIONALITY_COLUMN: "object",
    DEPARTURE_AIRPORT_NAME_COLUMN: "object",
    DEPARTURE_AIRPORT_CODE_COLUMN: "object",
    DEPARTURE_COUNTRY_NAME_COLUMN: "object",
    DEPARTURE_DATE_COLUMN: "object",
    ARRIVAL_AIRPORT_NAME_COLUMN: "object",
    ARRIVAL_AIRPORT_CODE_COLUMN: "object",
    ARRIVAL_COUNTRY_NAME_COLUMN: "object",
    FLIGHT_STATUS_COLUMN: "category",
    PILOT_FIRST_NAME_COLUMN: "object",
    PILOT_LAST_NAME_COLUMN: "object"
}

TOP_ROUTES_QUERY_NAME = "Top 10 Routes"
MONTHLY_FLIGHTS_QUERY_NAME = "Monthly Flights"
AIRPORT_TRAFFIC_QUERY_NAME = "Airport Traffic"

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SQL_FOLDER = os.path.join(BASE_DIR, "sql")
REPORT_OUTPUT = os.path.join(BASE_DIR, "reports", "podsumowanie.pdf")

REPORT_QUERIES = {
    TOP_ROUTES_QUERY_NAME: "analysis1.sql",
    MONTHLY_FLIGHTS_QUERY_NAME: "analysis2.sql",
    AIRPORT_TRAFFIC_QUERY_NAME: "analysis3.sql"
}
